### ISSUE TITLE
Add button to favorite a ParkCard.  Button should change when favorited. (Leaf changing from transparent to green?)

### ISSUE THREAD

**Issue by jenziel** [Marisa5280/stretchTech#37]

**Comment by jenziel** [comment]
add parkCode as an id to the ParkCode

**Comment by Marisa5280** [comment]
to ParkCards.tsx
- Add [isFavorite, setIsFavorite] = useState(false) inside function
- in addToFavorites function: toggle isFavorite state: setFavorite(!isFavorite);
- conditional in addToFavorites function
    - if truthy (isFavorite === false){filter thru favorites for every park that isn’t the target park}
        - setFavorites with updated array
    - else (!isFavorite){setFavorites([…favorites, park])}
- for styling (Ternary conditional) on button: className={`favorite-button ${isFavorite  ? ‘favorite’ : ‘ ‘}`}
